title: Sojo's BLOG
description: A personal blog by Sojo
author: ActedKitten (Sojo)
url: https://actedkitten.github.io
baseurl: /blog

# Theme
theme: jekyll-theme-cayman

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown
