title: Sojo's BLOG
author: ActedKitten
url: https://actedkitten.github.io
baseurl: /blog

# Theme
theme: jekyll-theme-cayman

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown
